### ISSUE TITLE
create_signature_help: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by cixtor** [tomv564/LSP#606] opened 2019-06-07 07:31 UTC
Hello again @rwols [I reported a bug a few minutes ago](https://github.com/tomv564/LSP/issues/605) that is very similar to one that you [fixed 5+ months ago](https://github.com/tomv564/LSP/issues/494) but this one is also completely new, it just happens to throw the same message, but the backtrace is different. I’m using [gopls](https://github.com/golang/go/wiki/gopls) with [LSP 0.8.4](https://github.com/tomv564/LSP/releases/tag/0.8.4), and noticed the following crash while hovering a function name.

* Using **macOS** with **gopls** _(default configuration)_
* I installed LSP using “Package Control”
* Minimal reproduction steps: Same as the other bug, I am unable to reproduce this crash voluntarily, and when it happens I already forgot the steps that ended up in the crash. Often it’s because I triggered `textDocument/hover` or the “rename” command.

```
Error handling server payload
Traceback (most recent call last):
  File "LSP.sublime-package/plugin/core/rpc.py", line 149, in receive_payload
    self.response_handler(payload)
  File "LSP.sublime-package/plugin/core/rpc.py", line 168, in response_handler
    handler(response["result"])
  File "LSP.sublime-package/plugin/signature_help.py", line 97, in <lambda>
    lambda response: self.handle_response(response, point))
  File "LSP.sublime-package/plugin/signature_help.py", line 100, in handle_response
    self._help = create_signature_help(response)
  File "LSP.sublime-package/plugin/core/signature_help.py", line 114, in create_signature_help
    signatures = list(parse_signature_information(signature) for signature in response.get("signatures", []))
TypeError: 'NoneType' object is not iterable
```

I hope the backtrace is descriptive enough to fix it.

**Comment by tomv564** [comment] 2019-06-07 22:36
Thanks for reporting!

It looks like gopls is returning a SignatureHelp object with `signatures` field set to null (None) instead of an empty array - LSP assumes servers follow the spec and don't put None there: 

https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#signature-help-request-leftwards_arrow_with_hook

Might be this code:
https://github.com/golang/tools/blob/68211a626cca1068197e1fa98907659c722d4222/internal/lsp/signature_help.go#L39

I think it would be great if you can confirm what gopls is sending by turning on `log_payloads` and reproducing the issue. We can then decide if gopls or LSP needs a fix :)

**Comment by cixtor** [comment] 2019-06-08 02:28
Thank you @tomv564 I agree with you, the language server should comply with the specification. I’ve mentioned this to some **gopls** maintainers, and one of them submitted [this change](https://github.com/golang/tools/commit/eacb66d2a7c3d6b93b39f7224e6bef6a44cbe70e#diff-24513f16ae77b99b7814f11c99a9371c) to address the issue.

**Comment by tomv564** [comment] 2019-06-08 10:47
Change looks like it should do the job, I will assume the issue is fixed with their next release. Thanks for following up with them!

**Closed by tomv564** 2019-06-08 10:47 UTC
