### ISSUE TITLE
Problems with LSP (“couldn’t start pyls, disabling”, SublimeText)

### ISSUE THREAD

**Issue by technoiswatchingyou** [tomv564/LSP#178] opened 2017-10-18 01:40 UTC
Hi

So problem is that "pyls" do not starting with Sublime: "couldn't start pyls, disabling". But if i restart server manually (LSP: Restart Servers) everything is ok for opened Sublime session. What can be reason for this? LSP is globally enabled. Recently i installed LSP and everything was fine.

Thanks for help.

MacOS 10.13.1
SublimeText v3.0, buil 3143

**Comment by braver** [comment] 2017-10-18 11:38
Sounds like a duplicate of https://github.com/tomv564/LSP/issues/147?

**Comment by rwols** [comment] 2017-10-18 11:57
Better make link to here too: https://github.com/SublimeTextIssues/Core/issues/1877

**Comment by tomv564** [comment] 2017-10-21 10:02
As commented on earlier, this is a duplicate. @technoiswatchingyou I hope you found the info you needed in the documentation or issue #147, otherwise please leave feedback in that issue.

**Closed by tomv564** 2017-10-21 10:02 UTC
