### ISSUE TITLE
Buffering while typing querySelector or addEventListener

### ISSUE THREAD

**Issue by luka-lazov** [tomv564/LSP#232] opened 2017-12-28 09:56 UTC
When I type `document.querySelector` and open the parentheses, I am still typing but the editor is frozen until it shows the tooltip: 

Current behavior:

![output1](https://user-images.githubusercontent.com/22029477/34407209-7238d89e-ebbd-11e7-9ab3-4031e1f2b392.gif)

![output2](https://user-images.githubusercontent.com/22029477/34407202-69e453bc-ebbd-11e7-89e0-a07c06d77d21.gif)

Expected behavior:
No buffer at all

![tern1](https://user-images.githubusercontent.com/22029477/34407233-977baca8-ebbd-11e7-84df-12b940035cbc.gif)

**Comment by tomv564** [comment] 2017-12-29 12:37
It looks like the signature help request is synchronous and taking an extremely long time to complete.
For performance issues, have you tried https://www.npmjs.com/package/typescript-lsp or my own https://github.com/tomv564/lsp-tsserver ? 

By the way, again nice captures. For the expected behaviour, are you editing the recorded frames or did you record an example where the issue didn't occur?

**Comment by luka-lazov** [comment] 2017-12-29 14:32
Currently for JavaScript development I am using [tern](https://github.com/ternjs/tern_for_sublime), but I want to give LSP a try, and now I want to address some issues that keeps me away from it. Tern is similar to LSP, but only for JavaScript, it has nothing to do with LSP. 

> For the expected behaviour, are you editing the recorded frames or did you record an example where the issue didn't occur?

Tern was show in the 3 screenshot. Buffering happens every time when I use `querySelector`, `querySelectorAll`, `addEventListener` in LSP.

The language server that is used in the first two screenshots is  [github:sourcegraph/javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver).

So I tried your language server https://github.com/tomv564/lsp-tsserver, buffering happens with it too. 
Tried to set up  https://www.npmjs.com/package/typescript-lsp, but could't get it running. The server starts, but no auto completion.

**Comment by tomv564** [comment] 2017-12-29 15:36
It's possible that typescript-lsp choses not to support javascript files.
Tern is great, jsts has enough issues with eg. Flow that there is probably a solid user base for an LSP wrapper around tern.
But, knowing the issue is reproducible in lsp-tsserver then I'll investigate LSP first!

**Comment by tomv564** [comment] 2018-01-09 23:17
This is likely an issue with a complex signature being rendered with syntax highlighting. 
`querySelector`'s second overload renders properly without a hang:

<img width="662" alt="screen shot 2018-01-09 at 23 44 00" src="https://user-images.githubusercontent.com/4395832/34747148-43b99b96-f597-11e7-9f17-3f28b263f935.png">

But the server sends this enormous signature for the first (default) overload:

<img width="797" alt="screen shot 2018-01-09 at 23 53 56" src="https://user-images.githubusercontent.com/4395832/34747414-70d72bec-f598-11e7-9520-8db6bcd836d0.png">

Even with syntax highlighting, rendering this popup locks up the Sublime UI for a second or more.
I've added a workaround this for the time being by truncating and not highlighting long signatures (>400 characters) in https://github.com/tomv564/LSP/commit/c9d0fd4bdb5e947d2619b183802a91e30c121751.

Please let me know if latest master fixes your problem!

**Comment by luka-lazov** [comment] 2018-01-10 08:44
My laptops screen died.
As soon as I get it replaced, I will try it and I will notify you.

**Comment by luka-lazov** [comment] 2018-01-15 10:54
This commit https://github.com/tomv564/LSP/commit/c9d0fd4bdb5e947d2619b183802a91e30c121751 fixes the freezing :) 

![output3](https://user-images.githubusercontent.com/22029477/34938979-806714ea-f9ea-11e7-9f71-f456c543c9ec.gif)

This issue can be closed. 
And thank you :)

**Comment by tomv564** [comment] 2018-01-15 19:18
There might be something to be fixed in mdpopups here, but the typescript server produces such a weird case that I'll close this issue for now.

**Closed by tomv564** 2018-01-15 19:18 UTC
