### ISSUE TITLE
PHP docblock hover requests not made

### ISSUE THREAD

**Issue by muglug** [tomv564/LSP#625] opened 2019-06-23 15:06 UTC
Hey! I've made a PHP language server over at https://github.com/vimeo/psalm which I'm using with MacOS 10.14.5.

The latest master of my project has support for go-to-symbol-definition on individual docblock types, but the hover request is never made.

It works in VS Code, which makes me think it's a problem with Sublime's PHP syntax file, but I just want to check there's nothing further I can do.

Example code:

```php
/**
 * @var Foo\Bar\Baz|null <-- hovering over Foo\Bar\Baz does not trigger a hover request
 */
$a = null;
```

**Comment by jfcherng** [comment] 2019-06-23 15:47
I don't think `tomv564/LSP` sends a request when hovering on a comment in any programming language.

**Comment by rwols** [comment] 2019-06-23 17:47
Indeed, `comment` and `string` scopes are ignored: https://github.com/tomv564/LSP/blob/master/plugin/hover.py#L21

**Comment by muglug** [comment] 2019-06-23 18:49
Is this something that you’d accept a PR to change? Like, if the comment was parsed (and I have a written-in-PHP comment parser that could probably be ported to python relatively trivially) the hover blacklist could be more selective.

**Comment by rwols** [comment] 2019-06-23 19:16
Well, the idea was I think that when we didn't have those blacklisted scopes, people would complain about popups at their mouse cursor constantly saying "No description available". Keep in mind that this plugin works across multiple languages.

Personally I would think a more selective scope at the syntax level would be appropriate. e.g. we could scope such JavaDoc style doc-blocks as `documentation.block.php` instead of `comment.block.php`. So that would mean changing the shipped PHP.sublime-syntax file and detecting doc-blocks as actual doc-blocks. It just so happens that @jfcherng is a regular contributor for that syntax ;)

Although now that I think about it a little bit more, people's color schemes would probably start breaking with such a change as nobody colors a `documentation` scope. So probably a better idea would be to add a `meta.documentation.php` scope or something like that. Then we can change the `NO_HOVER_SCOPES` into `comment - meta.documentation` give or take.

Note that one can also run the `lsp_hover` command manually via a keybinding.

**Comment by rwols** [comment] 2019-06-23 19:33
Perhaps another solution is to remove the `NO_HOVER_SCOPES` logic entirely, and then change the "No description available" popup into a status-bar message instead.

**Comment by tomv564** [comment] 2019-06-24 03:21
Duplicate of #607

**Comment by tomv564** [comment] 2019-08-26 09:38
Fix for this is in master, next release on Package Control will contain it.

**Closed by tomv564** 2019-08-26 09:38 UTC
Labels: enhancement
