### ISSUE TITLE
Completions stop working after server error.

### ISSUE THREAD

**Issue by deathaxe** [tomv564/LSP#140] opened 2017-10-02 09:15 UTC
In some situations an completions request seems to get out of sync with the document, which triggers the following server error.

```
LSP: Got error from server:  {'message': 'Server error', 'code': -32000, 'data': {'message': '`column` parameter is not in a valid range.', 'type': 'ValueError', 'args': ['`column` parameter is not in a valid range.']}}
```

This error causes completions to stop working at all. LSP no longer requests completions. With `log_debug: true` the the only visible telegram to the server is 

```
LSP: notify: textDocument/didChange
```

The only way to restore from that state is to restart ST. Neither reloading the plugin nor forcing the python-language-server down to get it restarted works.

Log before/without error:

```
LSP: notify: textDocument/didChange
LSP: request 3: textDocument/completion 
LSP: got json:  {"result":{"isIncomplete":false,"items":[{"label":"set","kind":7,"detail":"class set","documentation":"set() -> new empty set object\nset(iterable) -> new set object\n\nBuild an unordered collection o ...
LSP: got json:  {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Apps/Sublime/Data/Packages/GitGutter/modules/compare.py","diagnostics":[{"source":"pyflakes","range":{"start":{"line":137,"chara ...
```

**Comment by tomv564** [comment] 2017-10-02 16:05
Might be worth checking if #134 is related. 

This `column parameter is not in a valid range.` error has been happening with pyls for a while.
A `pyls` build that traps this error and logs the document content might be helpful.

**Comment by deathaxe** [comment] 2017-10-02 19:29
The most efficient way to reproduce this issue in my case was right after starting ST. If I start working too quickly, I can crash the server for sure. During this period, ST's plugin_host is still quite busy with several background tasks. I enabled debug logging on both pyls and LSP with following results.

What I did to get it fail for sure was (I know it might not be a common use case 😉 ):

1. Start ST
2. quickly after startup start typing `sublime.` and delete it several times.

LSP log

```
LSP: global clients:  ['pyls=True']
LSP: no clients found for window 2
LSP: no clients found for window 2
LSP: starting in C:\Apps\Sublime\Data\Packages
LSP: starting ['pyls', '-v', '--log-file', 'c:/data/pyls.log']
LSP: request 1: initialize 
LSP: client registered for window 2 {'pyls': <LSP.main.Client object at 0x00000196F416A1D0>}
reloading plugin Exalt.impl.plugin
reloading plugin Exalt.impl.validator
reloading plugin Exalt.impl.formatter
LSP: request 2: textDocument/completion 
LSP: got json:  {"result":{"capabilities":{"codeActionProvider":true,"codeLensProvider":{"resolveProvider":false},"completionProvider":{"resolveProvider":false,"triggerCharacters":["."]},"documentFormattingProvider": ...
LSP: notify: initialized

***
A File Icon: Please restart Sublime Text for the applied icons to take effect ...
***

indexing [job 2]: no files were indexed out of the 2 queued, abandoning crawl
LSP: notify: textDocument/didOpen
LSP: got json:  {"error":{"code":-32000,"message":"Server error","data":{"type":"KeyError","args":["file:///C:/Apps/Sublime/Data/Packages/LSP/main.py"],"message":"'file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'"} ...
LSP: Got error from server:  {'code': -32000, 'message': 'Server error', 'data': {'message': "'file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'", 'args': ['file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'], 'type': 'KeyError'}}
LSP: got json:  {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Apps/Sublime/Data/Packages/LSP/main.py","diagnostics":[{"source":"mypy","range":{"start":{"line":2541,"character":9},"end":{"lin ...
LSP: notify: textDocument/didChange
LSP: got json:  {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Apps/Sublime/Data/Packages/LSP/main.py","diagnostics":[{"source":"mypy","range":{"start":{"line":2541,"character":9},"end":{"lin ...
LSP: notify: textDocument/didChange
LSP: notify: textDocument/didChange
LSP: got json:  {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Apps/Sublime/Data/Packages/LSP/main.py","diagnostics":[{"source":"mypy","range":{"start":{"line":2541,"character":0},"end":{"lin ...
LSP: got json:  {"method":"textDocument/publishDiagnostics","params":{"uri":"file:///C:/Apps/Sublime/Data/Packages/LSP/main.py","diagnostics":[{"source":"mypy","range":{"start":{"line":2541,"character":9},"end":{"lin ...
```

pyls.log
```
2017-10-02 21:18:55,264 UTC - INFO - pyls.language_server - Starting PythonLanguageServer IO language server
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_completion from <module 'pyls.plugins.completion' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\completion.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_definition from <module 'pyls.plugins.definition' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\definition.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_hover from <module 'pyls.plugins.hover' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\hover.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_references from <module 'pyls.plugins.references' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\references.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_signature_help from <module 'pyls.plugins.signature' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\signature.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin jedi_symbols from <module 'pyls.plugins.symbols' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\symbols.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin mccabe from <module 'pyls.plugins.mccabe_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\mccabe_lint.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin pycodestyle from <module 'pyls.plugins.pycodestyle_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pycodestyle_lint.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin pydocstyle from <module 'pyls.plugins.pydocstyle_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pydocstyle_lint.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin pyflakes from <module 'pyls.plugins.pyflakes_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pyflakes_lint.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin yapf from <module 'pyls.plugins.format' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\format.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Loaded pyls plugin pyls_mypy from <module 'pyls_mypy.plugin' from 'c:\\apps\\python36\\lib\\site-packages\\pyls_mypy\\plugin.py'>
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Updated settings to {'plugins': {'pydocstyle': {'enabled': False}}}
2017-10-02 21:18:55,529 UTC - INFO - pyls.config - Disabled plugins: [<module 'pyls.plugins.pydocstyle_lint' from 'c:\\apps\\python36\\lib\\site-packages\\pyls\\plugins\\pydocstyle_lint.py'>]
2017-10-02 21:18:55,670 UTC - ERROR - pyls.language_server - CAUGHT
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 125, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 59, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 18, in _hook
    doc = self.workspace.get_document(doc_uri) if doc_uri else None
  File "c:\apps\python36\lib\site-packages\pyls\workspace.py", line 48, in get_document
    return self._docs[doc_uri]
KeyError: 'file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'
2017-10-02 21:18:55,685 UTC - ERROR - jsonrpc.manager - API Exception: {'type': 'KeyError', 'args': ('file:///C:/Apps/Sublime/Data/Packages/LSP/main.py',), 'message': "'file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'"}
Traceback (most recent call last):
  File "c:\apps\python36\lib\site-packages\jsonrpc\manager.py", line 108, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\language_server.py", line 66, in wrapped
    return func(*args, **kwargs)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 125, in m_text_document__completion
    return self.completions(textDocument['uri'], position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 59, in completions
    completions = self._hook('pyls_completions', doc_uri, position=position)
  File "c:\apps\python36\lib\site-packages\pyls\python_ls.py", line 18, in _hook
    doc = self.workspace.get_document(doc_uri) if doc_uri else None
  File "c:\apps\python36\lib\site-packages\pyls\workspace.py", line 48, in get_document
    return self._docs[doc_uri]
KeyError: 'file:///C:/Apps/Sublime/Data/Packages/LSP/main.py'
2017-10-02 21:18:57,607 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:8 W292 no newline at end of file
2017-10-02 21:18:57,607 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:0 E305 expected 2 blank lines after class or function definition, found 0
2017-10-02 21:19:05,576 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:8 W292 no newline at end of file
2017-10-02 21:19:05,576 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:0 E305 expected 2 blank lines after class or function definition, found 0
2017-10-02 21:19:09,311 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:8 W292 no newline at end of file
2017-10-02 21:19:09,311 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:0 E305 expected 2 blank lines after class or function definition, found 0
2017-10-02 21:19:09,811 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:8 W292 no newline at end of file
2017-10-02 21:19:09,811 UTC - INFO - pyls.plugins.pycodestyle_lint - Got pycodestyle error at 2542:0 E305 expected 2 blank lines after class or function definition, found 0
```

It looks like the first `textDocument/completion` is sent before `textDocument/didOpen` which seems to confuse pyls.

Do you have some kind of state machine, which is meant to ensure `textDocument/didOpen` is sent first?

**Comment by deathaxe** [comment] 2017-10-02 19:36
Maybe related to 131 as well or even duplicate?

**Comment by tomv564** [comment] 2017-10-05 06:25
Likely caused by #134 (didChange sent too late) which is now fixed

**Comment by tomv564** [comment] 2017-10-20 05:58
Still seeing this

**Closed** 2017-10-22 15:07 UTC
