### ISSUE TITLE
Document how to setup with clangd

### ISSUE THREAD

**Issue by maddanio** [tomv564/LSP#398] opened 2018-08-24 08:55 UTC
Hi, I have clangd in a custom path. I have a cmake project. I also generated a compilation dB. I made a new server config by copying the clangd one and writing in it the full path. Also tried starting clangd manually in the dir with the dB: doesn’t work, debug log is not helpful, just says untracked document...

**Comment by rwols** [comment] 2018-08-25 23:48
Did you "enable" the server? (I'm not sure if that is still necessary.) In any case, here is my working configuration:

```
	"clients":
	{
		"clangd":
		{
			"enabled": true,
			"command":
			[
				"clangd",
				"-completion-style=plain",
				"-header-insertion-decorators=0",
				"-index"
			]
		}
         }
```

**Comment by maddanio** [comment] 2018-08-27 09:04
ok. trying that now. so my settings where:
```
{
  "clients": {
    "clangd":
    {
      "command": ["/usr/local/opt/llvm/bin/clangd"],
      "scopes": ["source.c", "source.c++", "source.objc", "source.objc++"],
      "syntaxes": ["Packages/C++/C.sublime-syntax", "Packages/C++/C++.sublime-syntax", "Packages/Objective-C/Objective-C.sublime-syntax", "Packages/Objective-C/Objective-C++.sublime-syntax"],
      "languageId": "objc++"
    },
  },    
}
```
i.e. those from the global settings with a fully qualified command path

**Comment by maddanio** [comment] 2018-08-27 09:16
ok, so after i removed those arguments and placed the compilation db manually in the projects root folder it works. my clangd (LLVM version 6.0.1) does not know them.
one second later it no longer works. i get:
```
LSP: config not available for view /Users/daniel/Documents/git/game-on-core/transforms/PlayerViewTransform.cpp
```

**Comment by rwols** [comment] 2018-08-27 11:30
Yes, the compile_commands.json file should be in the root of your project folder. Otherwise clangd cannot find it. Can you open the console and see if something goes wrong there? You can enable more logging using LSP's preferences.

**Comment by maddanio** [comment] 2018-08-27 12:02
i already enabled debug logging, and the above line is what i get, i.e. "LSP: config not available for view..."

**Comment by maddanio** [comment] 2018-08-27 12:03
btw in the docs i did not find anything about the compile_commands.json having to be there. thus my wish to improve the doc around clangd. it feels like a long way to get it to work. took me a day to find out clangd needs this db. and i can not find any docs as to how LSP starts the server, i.e. what directory.

**Comment by predragnikolic** [comment] 2018-08-27 17:42
Have you seen this? https://lsp.readthedocs.io/en/latest/#cc-clangd

**Comment by maddanio** [comment] 2018-08-28 08:54
I hadn't. But there is nothing new on there. I do have the compilation database.

**Comment by maddanio** [comment] 2018-08-28 08:59
ok, it turned out i typoed. and further it turns out that "enabled" : true is needed while it is never mentioned that it is. in the docs: "disable a language server globally, or per-project". anyhow, running now, will see what it can do :)

**Comment by rwols** [comment] 2018-08-28 09:32
Cool. I'm happy you got it working. Indeed maybe the docs need to be improved to mention the "enabled" key better.

**Comment by AmjadHD** [comment] 2018-09-26 20:29
how to set up the compilation_database.json in windows with msvc ?

**Comment by rwols** [comment] 2018-09-27 19:46
Hi @AmjadHD, I've googled a bit and perhaps your best bet may be https://www.sourcetrail.com/blog/export_clang_compilation_database_from_visual_studio_solution/

Another possibility is to use CMake and the Ninja generator (this is my personal favorite). This can generate compile_commands.json on windows out of the box with the `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` option.

**Comment by AmjadHD** [comment] 2018-09-28 08:41
how to include the ninja generator in the command ?

**Comment by AmjadHD** [comment] 2018-09-28 18:16
I did that and i got this error:
```console
C:\Users\User>cmake "C:\Users\User\Desktop\Tfach\Microbenchmarks" -G Ninja -DCMA
KE_EXPORT_COMPILE_COMMANDS=ON
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeTestCCompile
r.cmake:52 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/User/CMakeFiles/CMakeTmp

    Run Build Command:"C:/PROGRA~1/ninja/ninja.exe" "cmTC_03991"
    [1/2] Building C object CMakeFiles\cmTC_03991.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_03991.exe
    FAILED: cmTC_03991.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --
intdir=CMakeFiles\cmTC_03991.dir --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\l
ink.exe /nologo CMakeFiles\cmTC_03991.dir\testCCompiler.c.obj  /out:cmTC_03991.e
xe /implib:cmTC_03991.lib /pdb:cmTC_03991.pdb /version:0.0  /machine:X86  /debug
 /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib
 shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_03991.dir/manifest.res CMakeFiles\
cmTC_03991.dir/manifest.rc" failed (exit code 0) with the following output:
    Le fichier sp├®cifi├® est introuvable
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/User/CMakeFiles/CMakeOutput.log".
See also "C:/Users/User/CMakeFiles/CMakeError.log".
```
i'm new to this cmake thing and compilers as a hall.
note: that "Le fichier sp├®cifi├® est introuvable" means file not found.

**Comment by tomv564** [comment] 2018-10-03 14:38
I've clarified the need for setting "enabled" in the documentation, sorry you were bit by this change.
As the remainder of the issue is not specific to this package, I'd like to close it with two suggestions:

- Troubleshooting discussions can be done in gitter (https://gitter.im/SublimeLSP/)
- Given the number of configuration steps, someone could build a clangd-specific package for Sublime.

**Closed by tomv564** 2018-10-03 14:38 UTC
