### ISSUE TITLE
TypeError: unorderable types: NoneType() < NoneType()

### ISSUE THREAD

**Issue by django-wong** [tomv564/LSP#217] opened 2017-11-30 05:40 UTC
LSP 0.4.1
ST 3154 & 3155

When I type `$this->` this error occurs, and then autocomplete stop working

```
reloading settings Packages/LSP/LSP.sublime-settings
LSP: global clients: phpls=True
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP:  --> textDocument/completion
LSP: <--  textDocument/publishDiagnostics
Error handling server payload
Traceback (most recent call last):
  File "/Users/djangowong/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 119, in read_stdout
    self.response_handler(payload)
  File "/Users/djangowong/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/core/rpc.py", line 167, in response_handler
    self._response_handlers[handler_id](result)
  File "/Users/djangowong/Library/Application Support/Sublime Text 3/Packages/LSP/plugin/completion.py", line 255, in handle_response
    items = sorted(items, key=lambda item: item["sortText"])
TypeError: unorderable types: NoneType() < NoneType()

LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics
LSP:  --> textDocument/didChange
LSP: <--  textDocument/publishDiagnostics

```

**Comment by django-wong** [comment] 2017-11-30 05:41
This is the payload
```
LSP:      {'items': [{'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'fieldSearchable', 'detail': 'array', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Configure the Model', 'additionalTextEdits': None, 'filterText': None, 'label': 'model', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'create', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Update exists survey', 'additionalTextEdits': None, 'filterText': None, 'label': 'update', 'detail': '\\Modules\\Survey\\Models\\Survey', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'createSurveySetsAndQuestions', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Send survey invitation notification to all invited users', 'additionalTextEdits': None, 'filterText': None, 'label': 'send', 'detail': 'int', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Send survey expiring notification to users who has no response\nthis survey', 'additionalTextEdits': None, 'filterText': None, 'label': 'remind', 'detail': 'int', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'app', 'detail': '\\Illuminate\\Container\\Container', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'model', 'detail': '\\Illuminate\\Database\\Eloquent\\Model', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'fieldSearchable', 'detail': 'array', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'presenter', 'detail': '\\Prettus\\Repository\\Contracts\\PresenterInterface', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'validator', 'detail': '\\Prettus\\Validator\\Contracts\\ValidatorInterface', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Validation Rules', 'additionalTextEdits': None, 'filterText': None, 'label': 'rules', 'detail': 'array', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Collection of Criteria', 'additionalTextEdits': None, 'filterText': None, 'label': 'criteria', 'detail': '\\Illuminate\\Support\\Collection', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'skipCriteria', 'detail': 'bool', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'skipPresenter', 'detail': 'bool', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'scopeQuery', 'detail': '\\Closure', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': '__construct', 'detail': 'mixed', 'data': None, 'kind': 4, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'boot', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'resetModel', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Specify Model class name', 'additionalTextEdits': None, 'filterText': None, 'label': 'model', 'detail': 'string', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Specify Presenter class name', 'additionalTextEdits': None, 'filterText': None, 'label': 'presenter', 'detail': 'string', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Specify Validator class name of Prettus\\Validator\\Contracts\\ValidatorInterface', 'additionalTextEdits': None, 'filterText': None, 'label': 'validator', 'detail': 'null', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Set Presenter', 'additionalTextEdits': None, 'filterText': None, 'label': 'setPresenter', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'makeModel', 'detail': '\\Illuminate\\Database\\Eloquent\\Model', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'makePresenter', 'detail': '\\Prettus\\Repository\\Contracts\\PresenterInterface', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'makeValidator', 'detail': 'null|\\Prettus\\Validator\\Contracts\\ValidatorInterface', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Get Searchable Fields', 'additionalTextEdits': None, 'filterText': None, 'label': 'getFieldsSearchable', 'detail': 'array', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Query Scope', 'additionalTextEdits': None, 'filterText': None, 'label': 'scopeQuery', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve data array for populate field select', 'additionalTextEdits': None, 'filterText': None, 'label': 'lists', 'detail': '\\Illuminate\\Support\\Collection|array', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve data array for populate field select\nCompatible with Laravel 5.3', 'additionalTextEdits': None, 'filterText': None, 'label': 'pluck', 'detail': '\\Illuminate\\Support\\Collection|array', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Sync relations', 'additionalTextEdits': None, 'filterText': None, 'label': 'sync', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'SyncWithoutDetaching', 'additionalTextEdits': None, 'filterText': None, 'label': 'syncWithoutDetaching', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve all data of repository', 'additionalTextEdits': None, 'filterText': None, 'label': 'all', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Alias of All method', 'additionalTextEdits': None, 'filterText': None, 'label': 'get', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve first data of repository', 'additionalTextEdits': None, 'filterText': None, 'label': 'first', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve first data of repository, or return new Entity', 'additionalTextEdits': None, 'filterText': None, 'label': 'firstOrNew', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve first data of repository, or create new Entity', 'additionalTextEdits': None, 'filterText': None, 'label': 'firstOrCreate', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve all data of repository, paginated', 'additionalTextEdits': None, 'filterText': None, 'label': 'paginate', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Retrieve all data of repository, simple paginated', 'additionalTextEdits': None, 'filterText': None, 'label': 'simplePaginate', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by id', 'additionalTextEdits': None, 'filterText': None, 'label': 'find', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by field and value', 'additionalTextEdits': None, 'filterText': None, 'label': 'findByField', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by multiple fields', 'additionalTextEdits': None, 'filterText': None, 'label': 'findWhere', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by multiple values in one field', 'additionalTextEdits': None, 'filterText': None, 'label': 'findWhereIn', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by excluding multiple values in one field', 'additionalTextEdits': None, 'filterText': None, 'label': 'findWhereNotIn', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Save a new entity in repository', 'additionalTextEdits': None, 'filterText': None, 'label': 'create', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Update a entity in repository by id', 'additionalTextEdits': None, 'filterText': None, 'label': 'update', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Update or Create an entity in repository', 'additionalTextEdits': None, 'filterText': None, 'label': 'updateOrCreate', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Delete a entity in repository by id', 'additionalTextEdits': None, 'filterText': None, 'label': 'delete', 'detail': 'int', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Delete multiple entities by given criteria.', 'additionalTextEdits': None, 'filterText': None, 'label': 'deleteWhere', 'detail': 'int', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Check if entity has relation', 'additionalTextEdits': None, 'filterText': None, 'label': 'has', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Load relations', 'additionalTextEdits': None, 'filterText': None, 'label': 'with', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Add subselect queries to count the relations.', 'additionalTextEdits': None, 'filterText': None, 'label': 'withCount', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Load relation with closure', 'additionalTextEdits': None, 'filterText': None, 'label': 'whereHas', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Set hidden fields', 'additionalTextEdits': None, 'filterText': None, 'label': 'hidden', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'orderBy', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Set visible fields', 'additionalTextEdits': None, 'filterText': None, 'label': 'visible', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Push Criteria for filter the query', 'additionalTextEdits': None, 'filterText': None, 'label': 'pushCriteria', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Pop Criteria', 'additionalTextEdits': None, 'filterText': None, 'label': 'popCriteria', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Get Collection of Criteria', 'additionalTextEdits': None, 'filterText': None, 'label': 'getCriteria', 'detail': '\\Illuminate\\Support\\Collection', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Find data by Criteria', 'additionalTextEdits': None, 'filterText': None, 'label': 'getByCriteria', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Skip Criteria', 'additionalTextEdits': None, 'filterText': None, 'label': 'skipCriteria', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Reset all Criterias', 'additionalTextEdits': None, 'filterText': None, 'label': 'resetCriteria', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Reset Query Scope', 'additionalTextEdits': None, 'filterText': None, 'label': 'resetScope', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Apply scope in current Query', 'additionalTextEdits': None, 'filterText': None, 'label': 'applyScope', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Apply criteria in current Query', 'additionalTextEdits': None, 'filterText': None, 'label': 'applyCriteria', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Applies the given where conditions to the model.', 'additionalTextEdits': None, 'filterText': None, 'label': 'applyConditions', 'detail': 'void', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Skip Presenter Wrapper', 'additionalTextEdits': None, 'filterText': None, 'label': 'skipPresenter', 'detail': '$this', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': 'Wrapper result data', 'additionalTextEdits': None, 'filterText': None, 'label': 'parserResult', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'uploadFileExpireHours', 'detail': 'int', 'data': None, 'kind': 10, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': '__construct', 'detail': 'mixed', 'data': None, 'kind': 4, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': '模型Scope', 'additionalTextEdits': None, 'filterText': None, 'label': 'getModuleScope', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'datatables', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'advanceSearch', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'findWithoutFail', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'create', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'update', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'updateRelations', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}, {'documentation': None, 'additionalTextEdits': None, 'filterText': None, 'label': 'getUploadId', 'detail': 'mixed', 'data': None, 'kind': 2, 'sortText': None, 'insertText': None, 'textEdit': None, 'command': None}], 'isIncomplete': True}
```

**Comment by django-wong** [comment] 2017-11-30 05:49
Just tried 0.4.0, it works fine

**Comment by tomv564** [comment] 2017-11-30 07:26
Thanks for checking back, it was the completion list sorting functionality added in 0.4.1.

The cause is the PHP language server sending explicit 'null' values instead of just leaving out the 'sortText' field. Might be nice to report it, but I've just pushed a fix to handle this better in https://github.com/tomv564/LSP/commit/22cfd5fb6c4a1ad7bf8a1d0d3be02fd05cbf3e32.

As there is no way to workaround, I recommend you hop over 0.4.1 :) Thanks for reporting!

**Comment by django-wong** [comment] 2017-11-30 14:04
Thanks, it works!  There is another small issue, when I type fast, the completion comes later and some times it undo what I just typed (keywords in most case).

**Comment by tomv564** [comment] 2017-11-30 16:35
Thanks for reporting back, the completions issue I'll take together with issue #211 as they are closely related.

**Closed by tomv564** 2017-11-30 16:35 UTC
