### ISSUE TITLE
[TS] auto import stopped working

### ISSUE THREAD

**Issue by princemaple** [tomv564/LSP#593] opened 2019-05-24 07:59 UTC
* OS and language server: Windows, lsp-tsserver
* How you installed LSP (Package Control or from git?) PC

* Minimal reproduction steps: 
![problem](https://user-images.githubusercontent.com/1329716/58311908-71e62300-7e4d-11e9-9e75-ba96edb06c32.gif)

* Log:
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1082, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'show_status'
```

Something broke in 0.8.3?

**Comment by rwols** [comment] 2019-05-24 08:13
duplicate of https://github.com/tomv564/LSP/issues/592

**Closed by rwols** 2019-05-24 08:13 UTC
