### ISSUE TITLE
Disable diagnostic gutters

### ISSUE THREAD

**Issue by toxinu** [tomv564/LSP#97] opened 2017-09-13 15:52 UTC
Is there any way to disable diagnostic gutters?

Thanks!

**Comment by tomv564** [comment] 2017-09-13 18:17
No, but it would be trivial to add a setting to change from the current `"dot"` to `""` or `None`.
Can you describe the issue caused by the gutter marks? Is it a conflict with another package using regions to draw in the gutter?

**Comment by braver** [comment] 2017-09-16 11:46
> Is it a conflict with another package using regions to draw in the gutter?

There can be only one icon in the gutter. If you have a linter-style marks, vcs marks, bookmarks and something like BracketHighlighter and it becomes pretty complicated. GitGutter seems to have finally stopped hiding my bookmarks recently for instance.

So, I like having control over this and disable the marks for packages where I don't really need them. In this particular case years of Word and SublimeLinter have trained me to look for squiggly underlines and I find them more easily than the red dots in the gutter. I'd rather save the space for GitGutter.

**Comment by tomv564** [comment] 2017-09-16 18:50
Thanks for clarifying - let's add a setting for this!

**Comment by tomv564** [comment] 2017-09-17 07:41
Commit https://github.com/tomv564/LSP/commit/bb577d6ec9be2e5774d3634edef8aeb2be6fbcf7 introduced a `diagnostics_gutter_marker` setting, defaulted to "dot". It can be set to "" to not show gutter markers for diagnostics.

I noticed that GitGutter reliably overwrites LSP's gutter markers.

<img width="442" alt="screen shot 2017-09-17 at 09 18 04" src="https://user-images.githubusercontent.com/4395832/30518990-490aadd4-9b8c-11e7-9cf1-159c17884832.png">

To reverse this behaviour, you would have to add LSP's regions to protected_regions in GitGutter.sublime-settings:

```json
"protected_regions": [
  // include the default protected regions here
  "lsp_error",
  "lsp_warning",
  "lsp_info",
  "lsp_hint"
]
```
:+1: to GitGutter for implementing this.
- [ ] Before closing, add this to documentation.

**Comment by toxinu** [comment] 2017-09-20 13:04
Sorry for being late. @braver exactly explain the reason of my issue :-)

**Closed** 2017-09-29 17:26 UTC
