### ISSUE TITLE
Signature Help height too short (need to scroll)

### ISSUE THREAD

**Issue by FHTheron** [tomv564/LSP#646] opened 2019-07-09 12:27 UTC
I am not sure if this is SublimeText or LSP. The popup cuts off after about two lines.

* Ubuntu, ccls
* Package Control or git (both do the same)
* Create a function with many long parameters.

![Screenshot from 2019-07-08 15-11-41](https://user-images.githubusercontent.com/16208294/60887754-6d3aca00-a255-11e9-83e6-3aff595c57eb.png)

**Comment by AmjadHD** [comment] 2019-07-10 00:41
possible duplicate of #486

**Comment by tomv564** [comment] 2019-07-17 23:54
Closing duplicate, please follow the linked issue  for updates :)

**Closed by tomv564** 2019-07-17 23:54 UTC
Labels: duplicate, enhancement
