### ISSUE TITLE
running Build (from sublime) terminates server

### ISSUE THREAD

**Issue by kubaroth** [tomv564/LSP#218] opened 2017-12-01 05:40 UTC
Just noticed if I run Build (make) directly from Sublime LSP stops working. The Restart server is required. 
Here is the output:
```
LSP: <--  textDocument/publishDiagnostics
Running  make
LSP: LSP stderr process ended.
LSP: LSP stdout process ended.
LSP:  --> textDocument/didChange
Traceback (most recent call last):
  File "plugin.core.documents in /home/kuba/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 110, in <lambda>
  File "plugin.core.documents in /home/kuba/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 121, in purge_did_change
  File "plugin.core.documents in /home/kuba/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 195, in notify_did_change
  File "plugin.core.rpc in /home/kuba/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 62, in send_notification
  File "plugin.core.rpc in /home/kuba/.config/sublime-text-3/Installed Packages/LSP.sublime-package", line 71, in send_payload
OSError: [Errno 9] Bad file descriptor
```

**Comment by kubaroth** [comment] 2017-12-01 06:16
A stopgap solution which seems to work in my case is to bypass entire exception block:
```
        except BrokenPipeError as err:
            # sublime.status_message("Failure sending LSP server message, exiting")
            # exception_log("Failure writing payload", err)
            # self.process.terminate()
            # self.process = None
            pass
```
Not sure how harmful this change will be ;) 
My guess this is sending next request to the clangd server. Perhaps terminating the process in case of any issues is too severe...?

**Comment by tomv564** [comment] 2017-12-01 07:11
Hi, thanks for investigating!
Your guess is correct, after `make` was started, a content change was sent to `clangd` which failed.

Are you sure clangd survives the BrokenPipeError after you commented out the `process.terminate()` ?

The cause could possibly be `clangd` terminating on make, or the BrokenPipeError is a phantom error we need to handle more precisely.

**Comment by kubaroth** [comment] 2017-12-01 08:15
After the change I can still jump to definition (using lsp_symbol_definition) so clangd seems to still be running in the background.

**Comment by tomv564** [comment] 2018-01-15 21:26
Sorry for the slow response, but I've just merged some relevant changes to master and I'd like to narrow down what is happening here. 
If LSP's I/O crashes, LSP-based jump-to-definition should not be working anymore. If you can repro this issue, can you include a bit more from the console logging showing how `lsp_symbol_definition` is handled by clangd?

Thanks in advance!

**Comment by kubaroth** [comment] 2018-01-20 18:20
Thanks for keeping this on the radar. Sure thing I'll test it this week.

**Comment by tomv564** [comment] 2018-02-11 22:26
If this is still occurring, I would like to see some logs from clangd around the time that a brokenpipeerror occurs.

**Closed by tomv564** 2018-02-11 22:26 UTC
