### ISSUE TITLE
Renaming doesn't work.

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#391] opened 2018-08-08 12:58 UTC
Apparently there's a problem with LS providing `'documentChanges'`, the client works only with `'changes'`. although in the [LSP specifications](https://microsoft.github.io/language-server-protocol/specification#workspaceedit) it's said that:

> If the client can handle versioned document edits and if documentChanges are present, the latter are preferred over changes.

Error:
```
LSP:  --> textDocument/rename
LSP: initialize on open 2 C:\Users\User\Desktop\Tfach\LSP tests\test.jl
LSP: Already starting on this window: julials
LSP: <--  window/setStatusBusy
LSP: Unhandled notification: window/setStatusBusy
LSP:      {'changes': None, 'documentChanges': [{'edits': [{'range': {'end': {'character': 14, 'line': 50}, 'start': {'character': 7, 'line': 50}}, 'newText': 'SquaresVector'}, {'range': {'end': {'character': 15, 'line': 54}, 'start': {'character': 8, 'line': 54}}, 'newText': 'SquaresVector'}, {'range': {'end': {'character': 20, 'line': 55}, 'start': {'character': 13, 'line': 55}}, 'newText': 'SquaresVector'}, {'range': {'end': {'character': 19, 'line': 56}, 'start': {'character': 12, 'line': 56}}, 'newText': 'SquaresVector'}, {'range': {'end': {'character': 14, 'line': 57}, 'start': {'character': 7, 'line': 57}}, 'newText': 'SquaresVector'}, {'range': {'end': {'character': 11, 'line': 59}, 'start': {'character': 4, 'line': 59}}, 'newText': 'SquaresVector'}], 'textDocument': {'uri': 'file:///C:/Users/User/Desktop/Tfach/LSP%20tests/test.jl', 'version': 1}}]}
Error handling server payload
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 322, in receive_payload
    self.response_handler(payload)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/rpc.py", line 341, in response_handler
    self._response_handlers[handler_id](result)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/rename.py", line 37, in handle_response
    if len(changes) > 0:
TypeError: object of type 'NoneType' has no len()

LSP: <--  window/setStatusReady
LSP: Unhandled notification: window/setStatusReady
```
LS: [Julia's Language Server](https://github.com/JuliaEditorSupport/LanguageServer.jl).
OS: Win7-64bit.
ST: dev-3175.

**Comment by tomv564** [comment] 2018-08-08 21:40
This is a duplicate of #330, fixed in master but not yet released. I'll do a release soon, or feel free to run from master to help test!

**Closed by tomv564** 2018-08-08 21:40 UTC

**Comment by AmjadHD** [comment] 2018-08-08 22:55
Ah sorry didn't know about it !
