### ISSUE TITLE
disable function signature snippets

### ISSUE THREAD

**Issue by AmjadHD** [tomv564/LSP#569] opened 2019-04-16 23:36 UTC
The autocomplete popup shows function signatures as snippets, while that might be helpful, it is usually annoying for me, especially for functions with lots of optional arguments

![image](https://user-images.githubusercontent.com/33235928/56249724-1934a500-60ad-11e9-9bb7-42cb1bf815e2.png)

It'll be helpful to add an option to disable it, and an option to include only positional arguments, or to invoke it with a keybinding.

* OS: Windows 10
* How you installed LSP : Package Control
* Minimal reproduction steps:
![image](https://user-images.githubusercontent.com/33235928/56250643-80078d80-60b0-11e9-8e5b-57fa6acfd6ba.png)

![image](https://user-images.githubusercontent.com/33235928/56250449-c1e40400-60af-11e9-9e43-059eada56460.png)

**Comment by tomv564** [comment] 2019-04-17 09:25
Did you verify if your language server is responsible for this behaviour? It is unexpected that the "label" returned for each completion item would contain so much detail.

**Comment by AmjadHD** [comment] 2019-04-17 10:22
I don't know how to verify that. I use pyls v0.23.2, can you install it and see if it behaves the same ?

**Comment by rwols** [comment] 2019-04-17 12:15
This seems to be a duplicate of https://github.com/tomv564/LSP/issues/547 and was fixed by https://github.com/tomv564/LSP/pull/551.

**Closed by rwols** 2019-04-17 12:15 UTC
