### ISSUE TITLE
Exception triggered randomly on focusing document after switching projects

### ISSUE THREAD

**Issue by rchl** [tomv564/LSP#469] opened 2018-11-29 11:09 UTC
# Configuration
* LSP v0.7.3 (installed from Package Control)
* OSX Mojave
* LSP.sublime-settings:
```
	"clients":
	{
		"vue-ls":
		{
			"enabled": true,
			"command":
			[
				"vls"
			],
			"languageId": "vue",
			"scopes":
			[
				"text.html.vue"
			],
			"syntaxes":
			[
				"Packages/Vue Syntax Highlight/Vue Component.sublime-syntax"
			]
		}
	}
```

# Repro

1. Open vue file in the editor.
2. Switch to a different project (I'm using Project Manager to switch projects but should be the same with built-in project switching).
3. Switch back to initial project

# What happens

Exceptions are triggering in the console:

```
Error handling server payload
Traceback (most recent call last):
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 142, in receive_payload
    self.response_handler(payload)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/rpc.py", line 161, in response_handler
    self._response_handlers[handler_id](result)
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 175, in <lambda>
    lambda result: self._handle_shutdown_result(result))
  File "/Users/xxx/Library/Application Support/Sublime Text 3/Installed Packages/LSP.sublime-package/plugin/core/sessions.py", line 178, in _handle_shutdown_result
    self.client.exit()
AttributeError: 'NoneType' object has no attribute 'exit'

server: Vetur initialized
```

**Comment by predragnikolic** [comment] 2018-11-29 23:12
Maybe related #454, maybe :D

**Comment by predragnikolic** [comment] 2018-11-29 23:24
I am pretty sure that is the same problem as #448. It has been fixed with #454.

It you want, you can try out the latest master and see if the problem is gone :)

**Comment by rchl** [comment] 2018-11-30 10:39
Maybe new release coming up soon? I don't have much time right now to tinker with stuff.

**Comment by rwols** [comment] 2018-11-30 20:53
This seems to be something different maybe? Here, the self.client variable is none.

**Comment by rwols** [comment] 2018-11-30 20:55
Disregard that, self.client is none in https://github.com/tomv564/LSP/issues/448 too.

**Comment by tomv564** [comment] 2018-12-10 21:52
We should absolutely do a new release soon!

**Comment by rwols** [comment] 2019-03-02 22:50
So is this fixed now?

**Comment by tomv564** [comment] 2019-08-26 22:30
Assuming this was a duplicate, closing.

**Closed by tomv564** 2019-08-26 22:30 UTC
Labels: bug
